import Anthropic from '@anthropic-ai/sdk'
import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { createInterface } from 'node:readline/promises'
import { stdin as input, stdout as output } from 'node:process'
import { CORE_STRATAGEMS } from '../data/coreStratagems'
import type { DataManifest } from '../dataModel'
import { readManifest, writeManifest } from './emit'

/**
 * Offline mechanical-summary generation for faction stratagems.
 *
 * Replaces the roleplay-fluff `summary` fields on all stratagem entries with ultra-terse
 * mechanical descriptions generated by Claude (e.g. "-1 to AP on all incoming attacks").
 * Deduplicates the ~965 unique effect texts before calling the API so identical effects across
 * factions/shared sets are generated once and fanned out. Saves every accepted summary to
 * `docs/summary-overrides.json` so re-runs are instant (no API calls for already-reviewed effects).
 * When a generated summary is ambiguous (too long or hedging language), it pauses for human review
 * unless `--no-interactive` is set.
 *
 * Usage: `npm run ingest:summarise -- [--factions <slug,slug|all>] [--dry-run] [--no-interactive]`
 *
 * Prerequisites: `ANTHROPIC_API_KEY` must be set in the environment.
 * Run AFTER `npm run ingest:wahapedia` and `npm run ingest:dedup` so stratagems are already merged
 * and shared sets have been factored out.
 */

const DATA_DIR = join(process.cwd(), 'public', 'data')
const FACTIONS_DIR = join(DATA_DIR, 'factions')
const SHARED_DIR = join(DATA_DIR, 'shared')
const OVERRIDES_PATH = join(process.cwd(), 'docs', 'summary-overrides.json')

// ─── Types ────────────────────────────────────────────────────────────────────

type Args = {
  factions: string[] | 'all'
  dryRun: boolean
  interactive: boolean
}

/** Where in a JSON file a specific stratagem lives, so we can patch it in place. */
type Location = {
  filePath: string
  detIndex: number
  stratIndex: number
}

/** One unique effect text and all the file locations that contain it. */
type EffectEntry = {
  /** Stratagem name from the first occurrence — used for display only. */
  name: string
  effect: string
  locations: Location[]
}

/** Persisted cache: SHA-256(effect)[0:12] → accepted summary string. */
type Overrides = Record<string, string>

// ─── CLI args ─────────────────────────────────────────────────────────────────

function parseArgs(argv: string[]): Args {
  const args: Args = { factions: 'all', dryRun: false, interactive: true }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--factions') {
      const v = argv[++i]
      args.factions = v === 'all' ? 'all' : v.split(',').map((s) => s.trim()).filter(Boolean)
    } else if (a === '--dry-run') {
      args.dryRun = true
    } else if (a === '--no-interactive') {
      args.interactive = false
    }
  }
  return args
}

// ─── Deduplication map ────────────────────────────────────────────────────────

/** Stable 12-char hex key derived from effect text — used as the override cache key. */
function effectHash(effect: string): string {
  return createHash('sha256').update(effect).digest('hex').slice(0, 12)
}

/** Core stratagem names to skip — they already have hand-written mechanical summaries. */
const CORE_NAMES = new Set(CORE_STRATAGEMS.map((s) => s.name.toLowerCase()))

/**
 * Walk all faction and shared JSON files and build a deduplication map:
 *   effectHash → { name, effect, locations[] }
 *
 * Skips any stratagem whose name matches a core stratagem. Faction files are filtered by
 * `factionFilter`; shared files are always processed (they belong to multiple factions).
 */
async function buildDeduplicationMap(
  factionFilter: string[] | 'all',
): Promise<Map<string, EffectEntry>> {
  const map = new Map<string, EffectEntry>()

  const addStratagems = (filePath: string, detachments: { stratagems?: { name?: string; effect?: string }[] }[]) => {
    for (let dIdx = 0; dIdx < detachments.length; dIdx++) {
      const stratagems = detachments[dIdx].stratagems ?? []
      for (let sIdx = 0; sIdx < stratagems.length; sIdx++) {
        const strat = stratagems[sIdx]
        const name = strat.name ?? ''
        const effect = strat.effect ?? ''
        if (!effect || CORE_NAMES.has(name.toLowerCase())) continue
        const hash = effectHash(effect)
        if (!map.has(hash)) map.set(hash, { name, effect, locations: [] })
        map.get(hash)!.locations.push({ filePath, detIndex: dIdx, stratIndex: sIdx })
      }
    }
  }

  // Faction files — optionally filtered by id
  for (const file of await readdir(FACTIONS_DIR)) {
    if (!file.endsWith('.json')) continue
    const id = file.replace(/\.json$/, '')
    if (factionFilter !== 'all' && !factionFilter.includes(id)) continue
    const raw = JSON.parse(await readFile(join(FACTIONS_DIR, file), 'utf8'))
    addStratagems(join(FACTIONS_DIR, file), raw.detachments ?? [])
  }

  // Shared sets — always processed (they may contain stratagems for filtered factions)
  let sharedFiles: string[] = []
  try {
    sharedFiles = await readdir(SHARED_DIR)
  } catch {
    // no shared dir — skip silently
  }
  for (const file of sharedFiles) {
    if (!file.endsWith('.json')) continue
    const raw = JSON.parse(await readFile(join(SHARED_DIR, file), 'utf8'))
    addStratagems(join(SHARED_DIR, file), raw.detachments ?? [])
  }

  return map
}

// ─── Override cache ───────────────────────────────────────────────────────────

async function loadOverrides(): Promise<Overrides> {
  try {
    return JSON.parse(await readFile(OVERRIDES_PATH, 'utf8')) as Overrides
  } catch {
    return {}
  }
}

async function saveOverrides(overrides: Overrides): Promise<void> {
  await mkdir(join(process.cwd(), 'docs'), { recursive: true })
  // Stable sort by key so git diffs are minimal between runs
  const sorted = Object.fromEntries(Object.entries(overrides).sort(([a], [b]) => a.localeCompare(b)))
  await writeFile(OVERRIDES_PATH, JSON.stringify(sorted, null, 2) + '\n', 'utf8')
}

// ─── Claude API ───────────────────────────────────────────────────────────────

const EXAMPLES = `
Effect: "Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1."
Summary: -1 to AP on all incoming attacks.

Effect: "Until the end of the phase, weapons equipped by models in your unit have the [LETHAL HITS] ability."
Summary: Grant [LETHAL HITS] to unit's weapons.

Effect: "That unit can attempt to Fall Back, and when doing so its models can move through models from enemy units … That unit can then act normally this turn."
Summary: Fall Back through enemies; act normally this turn.
`.trim()

const SYSTEM_PROMPT = `You write ultra-terse mechanical summaries for Warhammer 40,000 stratagems.

Rules:
- Output ONLY the summary text — no explanation, no prefix like "Summary:". End with a single period.
- Be as short as possible while remaining unambiguous
- Compress aggressively: "-1 to AP" not "Worsen the Armour Penetration of all attacks by 1"
- Preserve game-term capitalisation exactly: [LETHAL HITS], INFANTRY, Battle-shocked, Engagement Range, Fall Back
- Never use hedging words like "may" or "depending on"

${EXAMPLES}`

async function generateSummary(
  client: Anthropic,
  name: string,
  effect: string,
): Promise<string> {
  const message = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 80,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: `Stratagem: ${name}\nEffect: ${effect}` }],
  })
  const block = message.content[0]
  if (block.type !== 'text') throw new Error(`Unexpected Claude response type: ${block.type}`)
  return block.text.trim()
}

// ─── Human-in-the-loop ────────────────────────────────────────────────────────

/** Flag a generated summary as needing human review. */
function isAmbiguous(summary: string): boolean {
  // Too long to scan at a glance, or contains hedging language / parenthetical clauses
  const MAX_LEN = 60
  const HEDGES = /\b(may|might|depending on|if applicable)\b|\([^)]+\)/i
  return summary.length > MAX_LEN || HEDGES.test(summary)
}

async function promptUser(
  rl: ReturnType<typeof createInterface>,
  name: string,
  effect: string,
  candidate: string,
): Promise<string> {
  const DIVIDER = '─'.repeat(60)
  console.log(`\n${DIVIDER}`)
  console.log(`Stratagem : ${name}`)
  console.log(`Effect    : ${effect.length > 200 ? effect.slice(0, 200) + '…' : effect}`)
  console.log(`\nGenerated : "${candidate}"`)
  console.log(`\n(Press Enter to accept, or type a replacement summary)`)
  console.log(DIVIDER)
  const answer = (await rl.question('> ')).trim()
  return answer || candidate
}

// ─── Write-back ───────────────────────────────────────────────────────────────

/** Content hash + byte count for one rewritten file — used to patch manifest.json. */
type FileHash = { sha256: string; bytes: number }

/**
 * Ensure a summary ends with exactly one period. Summaries can legitimately end with a closing
 * quote (inches: `6"`) or paren, so the period is appended after them. Idempotent.
 */
function withTerminalPeriod(summary: string): string {
  const trimmed = summary.trimEnd()
  return trimmed.endsWith('.') ? trimmed : `${trimmed}.`
}

/**
 * Apply the summary map to all JSON files in place.
 *
 * Reads each file once, patches all targeted stratagems, and writes back. Files are kept in their
 * original serialisation format (minified, as emitted by the other ingest CLIs).
 *
 * Returns `fileHashes` — the new sha256 + bytes for every file that was written — so the caller
 * can update manifest.json and keep the `?v=<sha256>` cache-bust URLs in sync.
 */
async function applyResults(
  effectMap: Map<string, EffectEntry>,
  results: Map<string, string>,
): Promise<{ filesUpdated: number; stratagsUpdated: number; fileHashes: Map<string, FileHash> }> {
  // Group by file path so each file is read + written exactly once
  const byFile = new Map<string, { detIndex: number; stratIndex: number; summary: string }[]>()
  for (const [hash, summary] of results) {
    for (const loc of effectMap.get(hash)!.locations) {
      const list = byFile.get(loc.filePath) ?? []
      list.push({ detIndex: loc.detIndex, stratIndex: loc.stratIndex, summary })
      byFile.set(loc.filePath, list)
    }
  }

  let filesUpdated = 0
  let stratagsUpdated = 0
  const fileHashes = new Map<string, FileHash>()

  for (const [filePath, updates] of byFile) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const raw: any = JSON.parse(await readFile(filePath, 'utf8'))
    for (const { detIndex, stratIndex, summary } of updates) {
      raw.detachments[detIndex].stratagems[stratIndex].summary = withTerminalPeriod(summary)
      stratagsUpdated++
    }
    // Write back minified — same format as other ingest CLIs produce
    const json = JSON.stringify(raw)
    await writeFile(filePath, json, 'utf8')
    fileHashes.set(filePath, {
      sha256: createHash('sha256').update(json).digest('hex'),
      bytes: Buffer.byteLength(json, 'utf8'),
    })
    filesUpdated++
  }
  return { filesUpdated, stratagsUpdated, fileHashes }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2))
  console.log('Generating mechanical stratagem summaries')
  if (args.dryRun) console.log('  (dry run — nothing will be written)')
  if (!args.interactive) console.log('  (non-interactive — ambiguous summaries accepted as-is)')

  const overrides = await loadOverrides()
  const effectMap = await buildDeduplicationMap(args.factions)
  const total = effectMap.size
  const cached = [...effectMap.keys()].filter((h) => overrides[h] !== undefined).length
  const toGenerate = total - cached

  console.log(
    `  ${total} unique effect(s) found — ${cached} already in cache, ${toGenerate} to generate`,
  )

  // Only need the API key when there are uncached effects to generate. Without one we still
  // apply every cached summary, then report what is missing (and exit non-zero) at the end.
  let client: Anthropic | null = null
  if (toGenerate > 0) {
    const apiKey = process.env.ANTHROPIC_API_KEY
    if (apiKey) {
      client = new Anthropic({ apiKey })
    } else {
      console.warn(
        '  ⚠ ANTHROPIC_API_KEY is not set (put it in .env.local) — applying cached summaries only;\n' +
          `    ${toGenerate} stratagem effect(s) will be left without a summary.`,
      )
    }
  }

  const rl = client && args.interactive ? createInterface({ input, output }) : null
  const totalToGenerate = toGenerate
  const skipped: string[] = []

  let generated = 0
  let humanReviewed = 0
  const results = new Map<string, string>()

  for (const [hash, entry] of effectMap) {
    // Use cached summary if available — skip the API call entirely
    if (overrides[hash] !== undefined) {
      results.set(hash, overrides[hash])
      continue
    }

    if (!client) {
      skipped.push(entry.name)
      continue
    }

    process.stdout.write(`  [${generated + 1}/${totalToGenerate}] ${entry.name} … `)

    const candidate = await generateSummary(client, entry.name, entry.effect)
    process.stdout.write(`"${candidate}"`)

    let final = candidate
    if (rl !== null && isAmbiguous(candidate)) {
      // Pause for human review — the generated summary is too long or sounds hedging
      final = await promptUser(rl, entry.name, entry.effect, candidate)
      humanReviewed++
    } else {
      process.stdout.write('\n')
    }

    overrides[hash] = final
    results.set(hash, final)
    generated++

    // Persist after each entry so partial progress survives an interruption
    if (!args.dryRun) await saveOverrides(overrides)
  }

  rl?.close()

  if (!args.dryRun) {
    const { filesUpdated, stratagsUpdated, fileHashes } = await applyResults(effectMap, results)

    // Patch manifest.json so the ?v=<sha256> cache-bust URLs stay in sync with the rewritten files.
    // next.config.ts sets Cache-Control: immutable on /data/factions/* and /data/shared/*; without
    // this update a browser or CDN would serve the old artifact under the old (now stale) URL forever.
    if (fileHashes.size > 0) {
      const manifest: DataManifest = await readManifest()
      const newManifest: DataManifest = {
        ...manifest,
        factions: manifest.factions.map((f) => {
          const hash = fileHashes.get(join(FACTIONS_DIR, `${f.factionId}.json`))
          return hash ? { ...f, sha256: hash.sha256, bytes: hash.bytes } : f
        }),
        sharedDetachments: manifest.sharedDetachments?.map((s) => {
          const hash = fileHashes.get(join(SHARED_DIR, `${s.id}.json`))
          return hash ? { ...s, sha256: hash.sha256, bytes: hash.bytes } : s
        }),
      }
      await writeManifest(newManifest)
    }

    console.log(
      `\n${filesUpdated} file(s) updated, ${stratagsUpdated} stratagem(s) rewritten` +
        ` (${generated} generated, ${cached} from cache, ${humanReviewed} human-reviewed).`,
    )
  } else {
    console.log(
      `\nDry run: ${results.size} summaries prepared` +
        ` (${generated} generated, ${cached} from cache) — nothing written.`,
    )
  }

  if (skipped.length > 0) {
    console.error(`\nNo summary for ${skipped.length} effect(s) (no API key): ${skipped.join(', ')}`)
    console.error('Set ANTHROPIC_API_KEY in .env.local and re-run `npm run ingest:summarise`.')
    process.exitCode = 1
  }
}

main().catch((err) => {
  console.error('\nSummarise failed:', err instanceof Error ? err.message : err)
  process.exit(1)
})
